### ISSUE TITLE
ungyr functionality

### ISSUE THREAD

**Issue by Watersdr** [matthewdoles/dad-bot#2]
https://imgur.com/a/GVitTxW

"Oh no...",
"This can't be right.",
"I hope this is what you wanted.",
"I always find something... anything...",
"Why did you want me to look this up?",
"I'm sorry...",
"Is this one okay?",
"I'm lost for words on this one.",
"Does this make us friends?",
"Please let this work...",
"Um...",
"Eh...",
"I didn't ask to be made.",
"I can't do anything right...",
":frowning:"

**Comment by matthewdoles** [comment]
Ungry functionality added 7/28/2019 - https://github.com/matthewdoles/dad-bot/commit/d56f1506ea976859e184d4a08e27a6001ad66bb4
